export const defaultTheme = {
  colors: {
    transparent: "transparent",
    white: "#FFFFFF",
    background: "#FAFAFA",
    "base-card": "#F3F2F2",
    "base-input": "#EDEDED",
    "base-button": "#E6E5E5",
    "base-hover": "#D7D5D5",
    "base-label": "#8D8686",
    "base-text": "#574F4D",
    "base-subtitle": "#403937",
    "base-title": "#272221",
    "purple-dark": "#4B2995",
    purple: "#8047F8",
    "purple-light": "#EBE5F9",
    "yellow-dark": "#C47F17",
    yellow: "#DBAC2C",
    "yellow-light": "#F1E9C9",
  },
  fontWeight: {
    "baloo-bold": 700,
    "baloo-extra": 800,
    "roboto-regular": 400,
    "roboto-bold": 700,
  },
  fontSize: {
    "title-xl": "3rem",
    "title-lg": "2rem",
    "title-md": "1.5rem",
    "title-sm": "1.25rem",
    "title-xs": "1.12rem",
    "text-xxl": "1.5rem",
    "text-xl": "1.25rem",
    "text-lg": "1.12rem",
    "text-md": "1rem",
    "text-sm": "0.875rem",
    "text-xs": "0.75rem",
    "text-xxs": "0.625rem",
  },
  /* 
  "components-button-g": "0.88rem",
  "components-button-s": "0.75rem", */
};
